---

- name: Upgrade all packages
  apt:
    upgrade: true
    state: latest

- name: Install common package dependencies
  package: name="{{ item }}" state=present
  become: true
  with_items: "{{ common_packages | default([]) }}"
  register: install_common_packages
  when: common_packages is defined
  tags:
    - install
