# Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up
---
version: '3'
services:

  app:
    image: common-test
    environment: &environment
      - STAGE=testing
    build:
      args:
        stage: test
